spring:
  docker:
    compose:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://groupmanagement.payerl.se:5432/groupmanagement
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate